### ISSUE TITLE
Update to dependency on elixir_auth_github to v1.5 and Update Phoenix to 1.6

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google-demo#6]
With the release of `elixir_auth_github` at `1.5.0` and Phoenix `1.6` we need to update this demo to confirm everything still works as expected. 

# Todo

+ [x] Update `Elixir` to `1.12.3`
+ [x] Update to Phoenix 1.6
  + [x] Deletes `package.json` and unnecessary node.js dependencies! 🎉 
+ [x] Update underlying dependency `elixir_auth_github` to `1.5.0` 📦 

Here's one we made earlier: https://github.com/dwyl/elixir-auth-github-demo/pull/18

The demo app is currently working on heroku using "old" version: https://elixir-auth-google-demo.herokuapp.com/
![image](https://user-images.githubusercontent.com/194400/136071341-c823e6b3-8713-4688-b42c-b5784b497680.png)

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/elixir-auth-google-demo/pull/7 assigned to @SimonLab
